project:
  name: react-app
  projectType: frontend
  language: javascript
  framework: react

runtime:
  version: "22"

build:
  tool: npm
  packageManager: npm
  installCommand: "npm ci"
  buildCommand: "npm run build"
  testCommand: "npm run test:ci"
  lintCommand: "npm run lint"
  artifactPath: "dist"
  coveragePath: "coverage"

quality:
  sonarEnabled: true

security:
  securityScanEnabled: true
  filesystemScan: true
  dependencyScan: true
  containerScan: true

docker:
  enabled: true
  dockerfile: Dockerfile
  imageName: react-app
  registry: ghcr

deployment:
  enabled: true
  type: container
  environment: dev
  target: vps

  container:
    port: 80
    hostPort: 9999

artifactRepository:
  enabled: false
  type: nexus
  format: raw
  url: ""
  repository: ""