sonar.projectKey=vkmohan2007_habitTracker
sonar.projectName=habitTracker

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.config.js

sonar.coverage.exclusions=src/main.jsx,src/test/**,**/*.test.jsx,**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8